fold=(0 1 2 3 4)

for i in "${fold[@]}"
do

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.2 \
        model.backbone.act=tanh \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=256 \
        model.readout.feature_encoder_dim=64 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.2 \
        model.readout.fc_act=tanh \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[0\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    sleep 660

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.2 \
        model.backbone.act=tanh \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=128 \
        model.readout.feature_encoder_dim=32 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.2 \
        model.readout.fc_act=tanh \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[1\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.4 \
        model.backbone.act=tanh \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=256 \
        model.readout.feature_encoder_dim=64 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.4 \
        model.readout.fc_act=tanh \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[2\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.4 \
        model.backbone.act=tanh \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=128 \
        model.readout.feature_encoder_dim=32 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.4 \
        model.readout.fc_act=tanh \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[3\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.2 \
        model.backbone.act=relu \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=256 \
        model.readout.feature_encoder_dim=64 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.2 \
        model.readout.fc_act=relu \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[4\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.2 \
        model.backbone.act=relu \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=128 \
        model.readout.feature_encoder_dim=32 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.2 \
        model.readout.fc_act=relu \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[5\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.4 \
        model.backbone.act=relu \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=256 \
        model.readout.feature_encoder_dim=64 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.4 \
        model.readout.fc_act=relu \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[6\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &

    python -m topobench \
        dataset=graph/FTD \
        model=graph/gatv4 \
        dataset.loader.parameters.adj_metric=wgcna \
        dataset.loader.parameters.adj_thresh=0.60 \
        dataset.loader.parameters.kfold=true \
        dataset.loader.parameters.num_folds=5 \
        dataset.loader.parameters.fold=$i \
        dataset.dataloader_params.batch_size=16 \
        model.feature_encoder.out_channels=1 \
        model.backbone.hidden_channels=\[16,32\],\[32,64\] \
        model.backbone.heads=\[3,3\] \
        model.backbone.dropout=0.4 \
        model.backbone.act=relu \
        model.backbone.weight_initializer=xavier \
        model.readout.graph_encoder_dim=128 \
        model.readout.feature_encoder_dim=32 \
        model.readout.fc_dim=\[128,64,32\] \
        model.readout.fc_dropout=0.4 \
        model.readout.fc_act=relu \
        optimizer.parameters.lr=0.001 \
        dataset.split_params.data_seed=0 \
        trainer.max_epochs=1000 \
        trainer.min_epochs=100 \
        trainer.check_val_every_n_epoch=1 \
        trainer.devices=\[7\] \
        logger.wandb.project=tests_TopoProteo \
        callbacks.early_stopping.patience=50 \
        tags="[TopoProteoGridSearch]" \
        --multirun &
done